---
common_apt_mirror: http://mirrors.aliyun.com/ubuntu
common_release_code: precise # 12.04
common_apt_cache_valid_time: 86400

common_timezone: Asia/Shanghai

common_locale_all: en_US.UTF-8
common_locale_lang: en_US.UTF-8
